# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'lesson_13_todo.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(553, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.deletebutton_PushButton = QtWidgets.QPushButton(self.centralwidget, clicked= lambda:self.delete_it())
        self.deletebutton_PushButton.setGeometry(QtCore.QRect(200, 60, 131, 31))
        self.deletebutton_PushButton.setObjectName("deletebutton_PushButton")
        self.additem_pushButton = QtWidgets.QPushButton(self.centralwidget, clicked=lambda:self.add_it())
        self.additem_pushButton.setGeometry(QtCore.QRect(10, 60, 121, 31))
        self.additem_pushButton.setObjectName("additem_pushButton")
        self.cleanallbutton_pushButton = QtWidgets.QPushButton(self.centralwidget, clicked=lambda :self.clear_it())
        self.cleanallbutton_pushButton.setGeometry(QtCore.QRect(390, 60, 141, 31))
        self.cleanallbutton_pushButton.setObjectName("cleanallbutton_pushButton")
        self.additem_LineWidget = QtWidgets.QLineEdit(self.centralwidget)
        self.additem_LineWidget.setGeometry(QtCore.QRect(12, 30, 521, 26))
        self.additem_LineWidget.setObjectName("additem_LineWidget")
        self.mylist_listWidget = QtWidgets.QListWidget(self.centralwidget)
        self.mylist_listWidget.setGeometry(QtCore.QRect(20, 110, 511, 411))
        self.mylist_listWidget.setObjectName("mylist_listWidget")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 553, 23))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "To Do list"))
        self.deletebutton_PushButton.setText(_translate("MainWindow", "Delete item from list"))
        self.additem_pushButton.setText(_translate("MainWindow", "Add item to list"))
        self.cleanallbutton_pushButton.setText(_translate("MainWindow", "Clear the list"))

    def add_it(self):
        item = self.additem_LineWidget.text()
        self.mylist_listWidget.addItem(item)

        #clear the itembox
        self.additem_LineWidget.setText('')


    def delete_it(self):
        clicked = self.mylist_listWidget.currentRow()
        #self.mylist_listWidget.addItem(str(clicked))

        # Delete selected row
        self.mylist_listWidget.takeItem(clicked)

    def clear_it(self):
        self.mylist_listWidget.clear()


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
